# Generated by Django 4.2.1 on 2023-06-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0003_alter_equipamento_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('matricula', models.IntegerField(unique=True)),
                ('curso', models.CharField(max_length=250)),
                ('data_emprestimo', models.DateTimeField(verbose_name='Inicio')),
                ('data_devolucao', models.DateTimeField(verbose_name='Fim')),
                ('observacao', models.CharField(max_length=500)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
            ],
        ),
    ]
