# Generated by Django 4.2.1 on 2023-06-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='curso',
            field=models.CharField(choices=[('0', 'Engenharia de Software'), ('1', 'Sistemas de Informação'), ('2', 'Engenharia de Produção'), ('3', 'Engenharia Sanitária'), ('4', 'Farmarcia'), ('5', 'Agronomia')], default='1', max_length=2),
        ),
    ]
