# Generated by Django 4.2.1 on 2023-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0004_alter_emprestimo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='observacao',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
