# Generated by Django 4.2.1 on 2023-10-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0005_alter_emprestimo_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='status_emprestimo',
            field=models.CharField(choices=[('D', 'Devolvido'), ('E', 'Emprestado')], default='E', max_length=1),
        ),
    ]
