# Generated by Django 4.2.1 on 2023-10-17 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0009_equipamento_created_at_alter_equipamento_codigo_and_more'),
        ('emprestimo', '0006_emprestimo_status_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='curso',
            field=models.CharField(choices=[('0', 'Engenharia de Software'), ('1', 'Sistemas de Informação'), ('2', 'Engenharia de Produção')], default='0', max_length=2, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Empréstimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='matricula',
            field=models.IntegerField(unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='observacao',
            field=models.CharField(blank=True, max_length=500, verbose_name='Observações'),
        ),
    ]
