# Generated by Django 4.2.1 on 2023-10-17 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0007_alter_emprestimo_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
