# Generated by Django 4.2.1 on 2023-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='situacao',
            field=models.CharField(choices=[('0', 'Indisponivel'), ('1', 'Disponivel')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('0', 'Indisponivel'), ('1', 'Disponivel')], default='1', max_length=2),
        ),
    ]
