# Generated by Django 4.2.1 on 2023-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0003_alter_equipamento_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='situacao',
            field=models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Ruim')], default='1', max_length=2),
        ),
    ]
