# Generated by Django 4.2.1 on 2023-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0004_alter_equipamento_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('0', 'Indisponível'), ('1', 'Disponível')], default='1', max_length=2),
        ),
    ]
