# Generated by Django 4.2.1 on 2023-06-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0006_alter_equipamento_patrimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
