# Generated by Django 4.2.1 on 2023-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0007_alter_equipamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
