# Generated by Django 4.2.1 on 2023-10-17 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0009_equipamento_created_at_alter_equipamento_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
